kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j-volume-claim
  namespace: prod-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: neo4j
