apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prod-monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/alertmanager/metrics'
  labels:
    name: alertmanager
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9093
    nodePort: 30001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: prod-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        args:
          - '-config.file=/etc/alertmanager/config.yml'
          - '-storage.path=/alertmanager'
          # The URL under which Alertmanager is externally reachable (for example,
          # if Alertmanager is served via a reverse proxy). Used for generating relative and
          # absolute links back to Alertmanager itself. If the URL has a path portion,
          # it will be used to prefix all HTTP endpoints served by Alertmanager.
          # If omitted, relevant URL components will be derived automatically.
          - '-web.external-url=https://alertmanager.cotoa.me/alertmanager'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: templates-volume
          mountPath: /etc/alertmanager-templates
        - name: storage
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - name: templates-volume
        configMap:
          name: alertmanager-templates
      - name: storage
        emptyDir: {}
