kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-volume
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: neo4j
  awsElasticBlockStore:
    volumeID: vol-05b933e3d2e1fe56a
    fsType: ext4
