apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cotoami
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cotoami
    spec:
      containers:
      - name: cotoami
        image: cotoami/cotoami:0fd9b63bbd7760392696a06b424a1fe49bd42b34
        ports:
        - containerPort: 80
